// Generated by services/triage/scripts/export_contracts.py; do not edit.
import { validateContract } from "./runtime";
import TriageRequestSchema from "../../services/triage/contracts/triage-request.schema.json";
import TriageResultSchema from "../../services/triage/contracts/triage-result.schema.json";
import TranscriptionRequestSchema from "../../services/triage/contracts/transcription-request.schema.json";
import TranscriptionResultSchema from "../../services/triage/contracts/transcription-result.schema.json";
import SessionInfoSchema from "../../services/triage/contracts/session-info.schema.json";
import TelemetryRequestSchema from "../../services/triage/contracts/telemetry-request.schema.json";
import TelemetryReceiptSchema from "../../services/triage/contracts/telemetry-receipt.schema.json";
import IncidentSnapshotSchema from "../../services/triage/contracts/incident-snapshot.schema.json";
import IncidentEventSchema from "../../services/triage/contracts/incident-event.schema.json";
import CommandReceiptSchema from "../../services/triage/contracts/command-receipt.schema.json";
import IncidentCommandSchema from "../../services/triage/contracts/incident-command.schema.json";
import MediaRequestSchema from "../../services/triage/contracts/media-request.schema.json";
import MediaReceiptSchema from "../../services/triage/contracts/media-receipt.schema.json";
import MediaResultSchema from "../../services/triage/contracts/media-result.schema.json";
import ContextSummarySchema from "../../services/triage/contracts/context-summary.schema.json";

export type AlertCommandInput = {
  "kind": "acknowledge" | "reject" | "resolve";
  "expected_revision": number;
  "alert_id": string;
  "note"?: string | null;
};

export type AlertEvent = {
  "alert_id": string;
  "kind": "assistance_request" | "possible_visible_weapon" | "visual_review";
  "claim": string;
  "source_id": string | null;
  "subject_id": string | null;
  "observed_at": string;
  "created_at": string;
  "evidence_refs": Array<string>;
  "priority": "urgent_review" | "review";
  "evidence_status": "human_reported" | "machine_observed" | "human_rejected";
  "attention": "unacknowledged" | "acknowledged";
  "disposition": "open" | "human_resolved";
  "freshness": "fresh" | "stale";
  "freshness_expires_at": string | null;
  "requires_human_review": true;
  "created_by": Attribution | null;
  "acknowledged_by": Attribution | null;
  "rejected_by": Attribution | null;
  "resolved_by": Attribution | null;
};

export type AssistanceCommandInput = {
  "kind": "assistance";
  "note": string;
  "source_id"?: string | null;
};

export type Attribution = {
  "principal_id": string;
  "role": "source" | "officer" | "dispatch" | "hospital";
  "at": string;
  "note": string | null;
};

export type AudioMediaRequestInput = {
  "schema_version"?: "2.0";
  "incident_id": string;
  "source_id": string;
  "boot_id": string;
  "sequence": number;
  "captured_at": string;
  "data_base64": string;
  "kind": "audio";
  "media_type": "audio/wav" | "audio/mp4" | "audio/aac" | "audio/mpeg" | "audio/webm" | "audio/ogg";
};

export type BoundingBox = {
  "x1": number;
  "y1": number;
  "x2": number;
  "y2": number;
};

export type CommandReceipt = {
  "schema_version": "2.0";
  "incident_id": string;
  "command_id": string;
  "revision": number;
  "alert_id": string | null;
  "report_id": string | null;
  "handoff_id": string | null;
};

export type ContextSummary = {
  "context_id": string;
  "incident_id": string;
  "source_id": string;
  "snapshot_revision": number;
  "generated_at": string;
  "evidence_refs": Array<string>;
  "summary": string;
  "limitations": Array<string>;
  "model": ModelProvenance;
  "requires_human_review": true;
  "context_semantics": "unverified_visual_context_no_action_authority";
};

export type Detection = {
  "label": string;
  "confidence": number;
  "bbox": BoundingBox;
};

export type FrameMediaRequestInput = {
  "schema_version"?: "2.0";
  "incident_id": string;
  "source_id": string;
  "boot_id": string;
  "sequence": number;
  "captured_at": string;
  "data_base64": string;
  "kind": "frame";
  "media_type": "image/jpeg" | "image/png" | "image/webp";
};

export type Hazard = {
  "category": "fire_smoke" | "traffic_collision" | "blocked_access" | "structural_damage" | "flooding" | "electrical_hazard" | "person_down" | "visible_weapon" | "other";
  "severity": "low" | "moderate" | "high" | "critical";
  "confidence": number;
  "visual_evidence": string;
  "uncertainty": string;
  "detection_indices": Array<number>;
};

export type HeartRateSampleInput = {
  "sample_id": string;
  "boot_id": string;
  "sequence": number;
  "measured_at": string;
  "kind": "heart_rate";
  "value": HeartRateValueInput;
};

export type HeartRateValue = {
  "bpm": number;
  "unit": "bpm";
  "measurement_origin": "watch_healthkit";
  "signal_quality": "unknown";
  "measured_until": string | null;
  "session_mode": "user_started_walking_workout" | null;
  "sample_origin": "healthkit_live_workout_statistics" | null;
};

export type HeartRateValueInput = {
  "bpm": number;
  "unit"?: "bpm";
  "measurement_origin"?: "watch_healthkit";
  "signal_quality"?: "unknown";
  "measured_until"?: string | null;
  "session_mode"?: "user_started_walking_workout" | null;
  "sample_origin"?: "healthkit_live_workout_statistics" | null;
};

export type HumanHandoff = {
  "handoff_id": string;
  "incident_id": string;
  "patient_id": string;
  "handoff_revision": number;
  "mechanism": string | null;
  "injuries": string | null;
  "signs": string | null;
  "treatments": string | null;
  "recorded_by": Attribution;
  "provenance": "human_reported";
  "delivery_status": "recorded_locally_not_transmitted";
};

export type IncidentCommand = AssistanceCommandInput | AlertCommandInput | SceneReportCommandInput | RevokeSceneReportCommandInput | SubmitHandoffCommandInput;

export type IncidentEvent = {
  "schema_version": "2.0";
  "event_id": string;
  "incident_id": string;
  "revision": number;
  "kind": "telemetry" | "assistance" | "alert_acknowledged" | "alert_rejected" | "alert_resolved" | "scene_reported" | "scene_report_revoked" | "visual_observed" | "transcript_observed" | "context_updated" | "source_reset" | "handoff_recorded";
  "recorded_at": string;
};

export type IncidentSnapshot = {
  "schema_version": "2.0";
  "incident_id": string;
  "revision": number;
  "generated_at": string;
  "sources": Array<SourceState>;
  "observations": Array<Observation>;
  "alerts": Array<AlertEvent>;
  "scene_reports": Array<SceneReport>;
  "patients": Array<PatientEnrollment>;
  "handoffs": Array<HumanHandoff>;
};

export type LocationSampleInput = {
  "sample_id": string;
  "boot_id": string;
  "sequence": number;
  "measured_at": string;
  "kind": "location";
  "value": LocationValueInput;
};

export type LocationValue = {
  "latitude": number;
  "longitude": number;
  "horizontal_accuracy_m": number;
  "speed_mps": number | null;
  "course_degrees": number | null;
};

export type LocationValueInput = {
  "latitude": number;
  "longitude": number;
  "horizontal_accuracy_m": number;
  "speed_mps"?: number | null;
  "course_degrees"?: number | null;
};

export type MediaReceipt = {
  "schema_version": "2.0";
  "media_id": string;
  "incident_id": string;
  "source_id": string;
  "kind": "frame" | "audio";
  "status": "accepted" | "replaced" | "duplicate";
  "processing_semantics": "admitted_not_processed";
};

export type MediaRequest = FrameMediaRequestInput | AudioMediaRequestInput;

export type MediaResult = {
  "media_id": string;
  "incident_id": string;
  "source_id": string;
  "kind": "frame" | "audio";
  "boot_id": string;
  "sequence": number;
  "captured_at": string;
  "processed_at": string;
  "status": "observed" | "unavailable";
  "evidence_refs": Array<string>;
  "detections": Array<Detection>;
  "transcript": TranscriptionResult | null;
  "models": Array<ModelProvenance>;
  "warnings": Array<string>;
  "timings_ms": Record<string, number>;
  "requires_human_review": true;
  "confidence_semantics": "uncalibrated_model_scores";
};

export type ModelProvenance = {
  "provider": "ollama" | "openai_compatible" | "ultralytics" | "faster_whisper";
  "model": string;
  "revision": string | null;
};

export type Observation = {
  "observation_id": string;
  "source_id": string;
  "measured_at": string;
  "received_at": string;
  "boot_id": string;
  "sequence": number;
  "provenance": "device_reported" | "machine_observed" | "unverified_model_context";
  "freshness": "fresh" | "stale" | "historical";
  "freshness_expires_at": string | null;
  "age_seconds": number;
  "warnings": Array<string>;
} & (
  { kind: "context"; value: ContextSummary; subject_id: null } |
  { kind: "heart_rate"; value: HeartRateValue; subject_id: string | null } |
  { kind: "location"; value: LocationValue; subject_id: null } |
  { kind: "source_health"; value: SourceHealthValue; subject_id: null } |
  { kind: "transcript"; value: MediaResult & { kind: "audio" }; subject_id: null } |
  { kind: "visual"; value: MediaResult & { kind: "frame" }; subject_id: null }
);

export type PatientEnrollment = {
  "patient_id": string;
  "incident_id": string;
  "display_name": string;
};

export type RevokeSceneReportCommandInput = {
  "kind": "revoke_scene_report";
  "expected_revision": number;
  "report_id": string;
  "note": string;
};

export type SampleReceipt = {
  "sample_id": string;
  "status": "accepted" | "historical" | "duplicate";
  "observation_id": string;
  "warnings": Array<string>;
};

export type SceneReport = {
  "report_id": string;
  "status": "reported_clear" | "restricted" | "unknown";
  "scope": string;
  "note": string;
  "reported_by": Attribution;
  "expires_at": string;
  "revoked_by": Attribution | null;
  "effective": boolean;
  "reassessment_required": boolean;
};

export type SceneReportCommandInput = {
  "kind": "scene_report";
  "expected_revision": number;
  "status": "reported_clear" | "restricted" | "unknown";
  "scope": string;
  "note": string;
  "valid_for_seconds": number;
};

export type SessionInfo = {
  "principal_id": string;
  "role": "source" | "officer" | "dispatch" | "hospital";
  "incident_ids": Array<string>;
  "source_ids": Array<string>;
  "patient_ids": Array<string>;
};

export type SourceHealthSampleInput = {
  "sample_id": string;
  "boot_id": string;
  "sequence": number;
  "measured_at": string;
  "kind": "source_health";
  "value": SourceHealthValueInput;
};

export type SourceHealthValue = {
  "availability": "available" | "interrupted" | "unavailable";
  "reason": string | null;
  "battery_fraction": number | null;
};

export type SourceHealthValueInput = {
  "availability": "available" | "interrupted" | "unavailable";
  "reason"?: string | null;
  "battery_fraction"?: number | null;
};

export type SourceState = {
  "source_id": string;
  "incident_id": string;
  "kind": "watch" | "camera" | "microphone" | "gps" | "device";
  "display_name": string;
  "wearer_id": string | null;
  "wearer_role": "responder" | "patient" | null;
  "availability": "unknown" | "available" | "interrupted" | "unavailable" | "stale";
  "last_received_at": string | null;
  "last_measured_at": string | null;
  "age_seconds": number | null;
  "sequence_gaps": number;
  "boot_id": string | null;
  "reason": string | null;
  "freshness_expires_at": string | null;
};

export type SubmitHandoffCommandInput = {
  "kind": "submit_handoff";
  "expected_revision": number;
  "patient_id": string;
  "mechanism"?: string | null;
  "injuries"?: string | null;
  "signs"?: string | null;
  "treatments"?: string | null;
};

export type TelemetryReceipt = {
  "schema_version": "2.0";
  "incident_id": string;
  "revision": number;
  "results": Array<SampleReceipt>;
};

export type TelemetryRequest = {
  "schema_version"?: "2.0";
  "incident_id": string;
  "source_id": string;
  "samples": Array<HeartRateSampleInput | LocationSampleInput | SourceHealthSampleInput>;
};

export type TranscriptSegment = {
  "start_seconds": number;
  "end_seconds": number;
  "text": string;
  "no_speech_probability": number | null;
};

export type TranscriptionRequest = {
  "audio_base64": string;
  "media_type": "audio/mp4" | "audio/aac" | "audio/mpeg" | "audio/wav" | "audio/webm" | "audio/ogg";
  "source_id": string;
  "captured_at": string;
  "incident_id"?: string | null;
  "language"?: string | null;
};

export type TranscriptionResult = {
  "schema_version": "1.0";
  "request_id": string;
  "source_id": string;
  "incident_id": string | null;
  "captured_at": string;
  "processed_at": string;
  "audio_sha256": string;
  "text": string;
  "speech_detected": boolean;
  "language": string | null;
  "language_probability": number | null;
  "duration_seconds": number;
  "segments": Array<TranscriptSegment>;
  "models": Array<ModelProvenance>;
  "warnings": Array<string>;
  "timings_ms": Record<string, number>;
  "requires_human_review": true;
  "confidence_semantics": "uncalibrated_model_scores";
  "transcript_semantics": "machine_hypothesis_not_verbatim_record";
};

export type TriageRequest = {
  "image_base64": string;
  "media_type": "image/jpeg" | "image/png" | "image/webp";
  "source_id": string;
  "captured_at": string;
  "incident_id"?: string | null;
  "allow_cloud"?: boolean;
};

export type TriageResult = {
  "schema_version": "1.0";
  "request_id": string;
  "source_id": string;
  "incident_id": string | null;
  "captured_at": string;
  "processed_at": string;
  "image_sha256": string;
  "status": "needs_review" | "insufficient_evidence";
  "review_priority": "immediate" | "urgent" | "routine" | "insufficient_evidence";
  "requires_human_review": true;
  "confidence_semantics": "uncalibrated_model_scores";
  "assessment": VisionAssessment | null;
  "detections": Array<Detection>;
  "models": Array<ModelProvenance>;
  "warnings": Array<string>;
  "timings_ms": Record<string, number>;
  "policy_version": "human-review-v1";
  "prompt_version": "visual-hazards-v1";
};

export type VisionAssessment = {
  "summary": string;
  "image_quality": "adequate" | "limited" | "unusable";
  "hazards": Array<Hazard>;
  "limitations": Array<string>;
};

export function parseTriageRequest(value: unknown): TriageRequest {
  validateContract(TriageRequestSchema, value);
  return value as TriageRequest;
}

export function parseTriageResult(value: unknown): TriageResult {
  validateContract(TriageResultSchema, value);
  return value as TriageResult;
}

export function parseTranscriptionRequest(value: unknown): TranscriptionRequest {
  validateContract(TranscriptionRequestSchema, value);
  return value as TranscriptionRequest;
}

export function parseTranscriptionResult(value: unknown): TranscriptionResult {
  validateContract(TranscriptionResultSchema, value);
  return value as TranscriptionResult;
}

export function parseSessionInfo(value: unknown): SessionInfo {
  validateContract(SessionInfoSchema, value);
  return value as SessionInfo;
}

export function parseTelemetryRequest(value: unknown): TelemetryRequest {
  validateContract(TelemetryRequestSchema, value);
  return value as TelemetryRequest;
}

export function parseTelemetryReceipt(value: unknown): TelemetryReceipt {
  validateContract(TelemetryReceiptSchema, value);
  return value as TelemetryReceipt;
}

export function parseIncidentSnapshot(value: unknown): IncidentSnapshot {
  validateContract(IncidentSnapshotSchema, value);
  return value as IncidentSnapshot;
}

export function parseIncidentEvent(value: unknown): IncidentEvent {
  validateContract(IncidentEventSchema, value);
  return value as IncidentEvent;
}

export function parseCommandReceipt(value: unknown): CommandReceipt {
  validateContract(CommandReceiptSchema, value);
  return value as CommandReceipt;
}

export function parseIncidentCommand(value: unknown): IncidentCommand {
  validateContract(IncidentCommandSchema, value);
  return value as IncidentCommand;
}

export function parseMediaRequest(value: unknown): MediaRequest {
  validateContract(MediaRequestSchema, value);
  return value as MediaRequest;
}

export function parseMediaReceipt(value: unknown): MediaReceipt {
  validateContract(MediaReceiptSchema, value);
  return value as MediaReceipt;
}

export function parseMediaResult(value: unknown): MediaResult {
  validateContract(MediaResultSchema, value);
  return value as MediaResult;
}

export function parseContextSummary(value: unknown): ContextSummary {
  validateContract(ContextSummarySchema, value);
  return value as ContextSummary;
}
