import type { JoinLink } from "./origin";

/**
 * The code a dispatcher points at when somebody asks to be on the map.
 *
 * Presentational and prop-driven on purpose: the QR is rendered on the server,
 * where the encoder lives, so nothing here reaches for the origin or ships an
 * encoder to the browser.
 */

const PROBLEM: Record<Exclude<JoinLink["joinability"], "ok">, { title: string; body: string }> = {
  loopback: {
    title: "Only this machine can open this",
    body: "The dashboard is running on localhost, which on somebody else's phone means that phone. Deploy it, or serve it on this machine's network address, and the code appears here.",
  },
  insecure: {
    title: "This address cannot ask for a location",
    body: "Browsers only hand out a position on a secure origin. This dashboard is on plain HTTP, so a phone would load the page and then be refused. Serve it over HTTPS and the code appears here.",
  },
};

export function JoinCard({ join }: { join: JoinLink | null }) {
  if (!join) return null;

  if (join.joinability !== "ok" || !join.qrSvg) {
    const problem = PROBLEM[join.joinability as Exclude<JoinLink["joinability"], "ok">];
    return (
      <aside className="join-card" aria-label="Put a phone on the map">
        <span className="panel-label">Add a unit</span>
        <p className="join-card__title">{problem.title}</p>
        <p className="join-card__body">{problem.body}</p>
      </aside>
    );
  }

  return (
    <aside className="join-card" aria-label="Put a phone on the map">
      <span className="panel-label">Add a unit</span>
      <div
        className="join-card__code"
        role="img"
        aria-label={`QR code linking to ${join.url}`}
        // Generated by the encoder on this server from a URL this server built.
        // No part of it comes from a request body or a user.
        dangerouslySetInnerHTML={{ __html: join.qrSvg }}
      />
      <p className="join-card__title">Scan to put your phone on the map</p>
      <p className="join-card__body">
        One tap, no sign-in. The phone publishes where it is until it is told to stop, and appears
        in the roster as a guest unit.
      </p>
      <code className="join-card__url">{join.url}</code>
    </aside>
  );
}
